# Trabalhando os dados

## Carregando o dataset

In [7]:
import pandas as pd
import numpy as np

In [8]:
ds = pd.read_csv('dataset/train.csv', header=0)
print(ds.shape)
ds.head(15)

/tmp/ipykernel_12074/2572705079.py:1: DtypeWarning: Columns (435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506) have mixed types. Specify dtype option on import or set low_memory=False.
  ds = pd.read_csv('dataset/train.csv', header=0)

(177024, 508)

,id,p_num,time,bg-5:55,bg-5:50,bg-5:45,bg-5:40,bg-5:35,bg-5:30,bg-5:25,...,activity-0:40,activity-0:35,activity-0:30,activity-0:25,activity-0:20,activity-0:15,activity-0:10,activity-0:05,activity-0:00,bg+1:00
0,p01_0,p01,06:10:00,NaN,NaN,9.6,NaN,NaN,9.7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.4
1,p01_1,p01,06:25:00,NaN,NaN,9.7,NaN,NaN,9.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.8
2,p01_2,p01,06:40:00,NaN,NaN,9.2,NaN,NaN,8.7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.5
3,p01_3,p01,06:55:00,NaN,NaN,8.7,NaN,NaN,8.4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.8
4,p01_4,p01,07:10:00,NaN,NaN,8.4,NaN,NaN,8.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.7
5,p01_5,p01,07:25:00,NaN,NaN,8.1,NaN,NaN,8.3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.4
6,p01_6,p01,07:40:00,NaN,NaN,8.3,NaN,NaN,9.6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.9
7,p01_7,p01,07:55:00,NaN,NaN,9.6,NaN,NaN,11.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.1
8,p01_8,p01,08:10:00,NaN,NaN,11.1,NaN,NaN,11.8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.1
9,p01_9,p01,08:25:00,NaN,NaN,11.8,NaN,NaN,12.8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.9
10,p01_10,p01,08:40:00,NaN,NaN,12.8,NaN,NaN,13.9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.4
11,p01_11,p01,08:55:00,NaN,NaN,13.9,NaN,NaN,14.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.1
12,p01_12,p01,09:10:00,NaN,NaN,14.2,NaN,NaN,14.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.3
13,p01_13,p01,09:25:00,NaN,NaN,14.2,NaN,NaN,15.4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.6
14,p01_14,p01,09:40:00,NaN,NaN,15.4,NaN,NaN,17.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.2

In [9]:
# ds.head(200).to_csv('dataset/train_slice.csv', index=False)

## Ordenando o dataset

In [10]:
ds['id_num'] = ds['id'].str[4:].astype(int)

In [11]:
ds = ds.sort_values(by=['p_num', 'id_num'], ascending=[True, True])
ds.head(15)

,id,p_num,time,bg-5:55,bg-5:50,bg-5:45,bg-5:40,bg-5:35,bg-5:30,bg-5:25,...,activity-0:35,activity-0:30,activity-0:25,activity-0:20,activity-0:15,activity-0:10,activity-0:05,activity-0:00,bg+1:00,id_num
0,p01_0,p01,06:10:00,NaN,NaN,9.6,NaN,NaN,9.7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.4,0
1,p01_1,p01,06:25:00,NaN,NaN,9.7,NaN,NaN,9.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.8,1
2,p01_2,p01,06:40:00,NaN,NaN,9.2,NaN,NaN,8.7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.5,2
3,p01_3,p01,06:55:00,NaN,NaN,8.7,NaN,NaN,8.4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.8,3
4,p01_4,p01,07:10:00,NaN,NaN,8.4,NaN,NaN,8.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.7,4
5,p01_5,p01,07:25:00,NaN,NaN,8.1,NaN,NaN,8.3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.4,5
6,p01_6,p01,07:40:00,NaN,NaN,8.3,NaN,NaN,9.6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.9,6
7,p01_7,p01,07:55:00,NaN,NaN,9.6,NaN,NaN,11.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.1,7
8,p01_8,p01,08:10:00,NaN,NaN,11.1,NaN,NaN,11.8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.1,8
9,p01_9,p01,08:25:00,NaN,NaN,11.8,NaN,NaN,12.8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.9,9
10,p01_10,p01,08:40:00,NaN,NaN,12.8,NaN,NaN,13.9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.4,10
11,p01_11,p01,08:55:00,NaN,NaN,13.9,NaN,NaN,14.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.1,11
12,p01_12,p01,09:10:00,NaN,NaN,14.2,NaN,NaN,14.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.3,12
13,p01_13,p01,09:25:00,NaN,NaN,14.2,NaN,NaN,15.4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.6,13
14,p01_14,p01,09:40:00,NaN,NaN,15.4,NaN,NaN,17.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.2,14

## Convertendo o time num inteiro crescente

In [ ]:
ds['minutes_since_start'] = (pd.to_datetime(ds['time'], format="%H:%M:%S").dt.hour * 60 + pd.to_datetime(ds['time'], format="%H:%M:%S").dt.minute)
ds.head(15)

,id,p_num,time,bg-5:55,bg-5:50,bg-5:45,bg-5:40,bg-5:35,bg-5:30,bg-5:25,...,activity-0:30,activity-0:25,activity-0:20,activity-0:15,activity-0:10,activity-0:05,activity-0:00,bg+1:00,id_num,minutes_since_start
0,p01_0,p01,06:10:00,NaN,NaN,9.6,NaN,NaN,9.7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.4,0,370
1,p01_1,p01,06:25:00,NaN,NaN,9.7,NaN,NaN,9.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.8,1,385
2,p01_2,p01,06:40:00,NaN,NaN,9.2,NaN,NaN,8.7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.5,2,400
3,p01_3,p01,06:55:00,NaN,NaN,8.7,NaN,NaN,8.4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.8,3,415
4,p01_4,p01,07:10:00,NaN,NaN,8.4,NaN,NaN,8.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.7,4,430
5,p01_5,p01,07:25:00,NaN,NaN,8.1,NaN,NaN,8.3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.4,5,445
6,p01_6,p01,07:40:00,NaN,NaN,8.3,NaN,NaN,9.6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.9,6,460
7,p01_7,p01,07:55:00,NaN,NaN,9.6,NaN,NaN,11.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.1,7,475
8,p01_8,p01,08:10:00,NaN,NaN,11.1,NaN,NaN,11.8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.1,8,490
9,p01_9,p01,08:25:00,NaN,NaN,11.8,NaN,NaN,12.8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.9,9,505
10,p01_10,p01,08:40:00,NaN,NaN,12.8,NaN,NaN,13.9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.4,10,520
11,p01_11,p01,08:55:00,NaN,NaN,13.9,NaN,NaN,14.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.1,11,535
12,p01_12,p01,09:10:00,NaN,NaN,14.2,NaN,NaN,14.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.3,12,550
13,p01_13,p01,09:25:00,NaN,NaN,14.2,NaN,NaN,15.4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.6,13,565
14,p01_14,p01,09:40:00,NaN,NaN,15.4,NaN,NaN,17.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.2,14,580

In [18]:
ds["time_circle"] = np.sin(2 * np.pi / 720 * ds['minutes_since_start']) + 2
ds.head(15)

,id,p_num,time,bg-5:55,bg-5:50,bg-5:45,bg-5:40,bg-5:35,bg-5:30,bg-5:25,...,activity-0:25,activity-0:20,activity-0:15,activity-0:10,activity-0:05,activity-0:00,bg+1:00,id_num,minutes_since_start,time_circle
0,p01_0,p01,06:10:00,NaN,NaN,9.6,NaN,NaN,9.7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,13.4,0,370,1.912844
1,p01_1,p01,06:25:00,NaN,NaN,9.7,NaN,NaN,9.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.8,1,385,1.783560
2,p01_2,p01,06:40:00,NaN,NaN,9.2,NaN,NaN,8.7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15.5,2,400,1.657980
3,p01_3,p01,06:55:00,NaN,NaN,8.7,NaN,NaN,8.4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.8,3,415,1.538251
4,p01_4,p01,07:10:00,NaN,NaN,8.4,NaN,NaN,8.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.7,4,430,1.426424
5,p01_5,p01,07:25:00,NaN,NaN,8.1,NaN,NaN,8.3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,11.4,5,445,1.324410
6,p01_6,p01,07:40:00,NaN,NaN,8.3,NaN,NaN,9.6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,11.9,6,460,1.233956
7,p01_7,p01,07:55:00,NaN,NaN,9.6,NaN,NaN,11.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15.1,7,475,1.156609
8,p01_8,p01,08:10:00,NaN,NaN,11.1,NaN,NaN,11.8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,17.1,8,490,1.093692
9,p01_9,p01,08:25:00,NaN,NaN,11.8,NaN,NaN,12.8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,17.9,9,505,1.046283
10,p01_10,p01,08:40:00,NaN,NaN,12.8,NaN,NaN,13.9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,17.4,10,520,1.015192
11,p01_11,p01,08:55:00,NaN,NaN,13.9,NaN,NaN,14.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,16.1,11,535,1.000952
12,p01_12,p01,09:10:00,NaN,NaN,14.2,NaN,NaN,14.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.3,12,550,1.003805
13,p01_13,p01,09:25:00,NaN,NaN,14.2,NaN,NaN,15.4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.6,13,565,1.023704
14,p01_14,p01,09:40:00,NaN,NaN,15.4,NaN,NaN,17.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,11.2,14,580,1.060307